import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useState } from "react";
const statusStyles = {
    raw: "bg-amber-100 text-amber-800",
    in_review: "bg-indigo-100 text-indigo-800",
    approved: "bg-emerald-100 text-emerald-800",
};
export function ChunkCard({ chunk, onTranslate, onUpdate }) {
    const [editing, setEditing] = useState(false);
    const [draft, setDraft] = useState(chunk.translated_text ?? "");
    const isFailed = chunk.editor_notes?.some((n) => n.startsWith("translation_failed"));
    return (_jsxs("article", { className: "rounded-lg border border-slate-200 bg-white overflow-hidden", children: [_jsxs("header", { className: "flex items-center justify-between px-4 py-2 border-b border-slate-100 bg-slate-50", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { className: "text-xs font-mono text-slate-500", children: ["#", chunk.sequence_number] }), _jsx("span", { className: `text-xs rounded-full px-2 py-0.5 font-medium ${statusStyles[chunk.status]}`, children: chunk.status }), isFailed && (_jsx("span", { className: "text-xs rounded-full px-2 py-0.5 font-medium bg-red-100 text-red-700", children: "failed" }))] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { onClick: onTranslate, className: "text-xs bg-indigo-600 hover:bg-indigo-700 text-white rounded px-2 py-1", children: chunk.translated_text ? "Re-translate" : "Translate" }), chunk.translated_text && chunk.status !== "approved" && (_jsx("button", { onClick: () => onUpdate({ status: "approved" }), className: "text-xs bg-emerald-600 hover:bg-emerald-700 text-white rounded px-2 py-1", children: "Approve" }))] })] }), _jsxs("div", { className: "grid md:grid-cols-2 divide-x divide-slate-100", children: [_jsxs("div", { className: "p-4", children: [_jsx("p", { className: "text-xs uppercase tracking-wider text-slate-400 mb-1", children: "Source (EN)" }), _jsx("p", { className: "text-sm whitespace-pre-wrap font-serif leading-relaxed", children: chunk.source_text })] }), _jsxs("div", { className: "p-4 bg-slate-50/40", children: [_jsxs("div", { className: "flex justify-between items-center mb-1", children: [_jsx("p", { className: "text-xs uppercase tracking-wider text-slate-400", children: "Translation (TR)" }), chunk.translated_text && !editing && (_jsx("button", { onClick: () => {
                                            setDraft(chunk.translated_text ?? "");
                                            setEditing(true);
                                        }, className: "text-xs text-indigo-600 hover:underline", children: "Edit" }))] }), editing ? (_jsxs("div", { children: [_jsx("textarea", { value: draft, onChange: (e) => setDraft(e.target.value), rows: 8, className: "w-full text-sm font-serif border border-slate-300 rounded p-2" }), _jsxs("div", { className: "flex gap-2 mt-2", children: [_jsx("button", { onClick: () => {
                                                    onUpdate({ translated_text: draft });
                                                    setEditing(false);
                                                }, className: "text-xs bg-indigo-600 text-white rounded px-2 py-1", children: "Save" }), _jsx("button", { onClick: () => setEditing(false), className: "text-xs text-slate-500", children: "Cancel" })] })] })) : chunk.translated_text ? (_jsx("p", { className: "text-sm whitespace-pre-wrap font-serif leading-relaxed", children: chunk.translated_text })) : (_jsx("p", { className: "text-sm text-slate-400 italic", children: "Not translated yet." })), chunk.editor_notes && chunk.editor_notes.length > 0 && (_jsxs("details", { className: "mt-3", children: [_jsxs("summary", { className: "text-xs text-slate-500 cursor-pointer", children: ["Editor notes (", chunk.editor_notes.length, ")"] }), _jsx("ul", { className: "mt-1 space-y-1 text-xs text-slate-600 list-disc list-inside", children: chunk.editor_notes.map((n, i) => (_jsx("li", { children: n }, i))) })] }))] })] })] }));
}
